# Generated by Django 4.2.7 on 2025-11-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "playlist_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="歌单ID"
                    ),
                ),
                (
                    "playlist_name",
                    models.CharField(max_length=128, verbose_name="歌单名称"),
                ),
                (
                    "playlist_cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="歌单封面",
                    ),
                ),
                (
                    "playlist_intro",
                    models.TextField(blank=True, null=True, verbose_name="歌单介绍"),
                ),
                (
                    "playlist_createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "playlist_updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否公开"),
                ),
                (
                    "playlist_creator",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌单",
                "verbose_name_plural": "歌单",
                "db_table": "playlists",
                "ordering": ["-playlist_createtime"],
            },
        ),
        migrations.CreateModel(
            name="StarPlaylist",
            fields=[
                (
                    "star_playlist_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏歌单ID"
                    ),
                ),
                (
                    "star_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        db_column="playlist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_by",
                        to="playlists.playlist",
                        verbose_name="歌单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏歌单",
                "verbose_name_plural": "收藏歌单",
                "db_table": "star_playlists",
                "indexes": [
                    models.Index(
                        fields=["user"], name="star_playli_user_id_64d016_idx"
                    ),
                    models.Index(
                        fields=["playlist"], name="star_playli_playlis_a1ffc1_idx"
                    ),
                ],
                "unique_together": {("user", "playlist")},
            },
        ),
        migrations.CreateModel(
            name="PlaylistSong",
            fields=[
                (
                    "playlist_songs_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="歌单歌曲项ID"
                    ),
                ),
                (
                    "add_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="添加时间"),
                ),
                ("order", models.IntegerField(default=0, verbose_name="排序顺序")),
                (
                    "playlist",
                    models.ForeignKey(
                        db_column="playlist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="playlists.playlist",
                        verbose_name="歌单",
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="in_playlists",
                        to="music.song",
                        verbose_name="歌曲",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌单歌曲",
                "verbose_name_plural": "歌单歌曲",
                "db_table": "playlist_songs",
                "ordering": ["order", "add_time"],
                "indexes": [
                    models.Index(
                        fields=["playlist"], name="playlist_so_playlis_ac7b12_idx"
                    ),
                    models.Index(
                        fields=["song"], name="playlist_so_song_id_5b2cc9_idx"
                    ),
                ],
                "unique_together": {("playlist", "song")},
            },
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["playlist_name"], name="playlists_playlis_c73c8c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["playlist_creator"], name="playlists_user_id_721754_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="playlist",
            index=models.Index(
                fields=["is_active"], name="playlists_is_acti_8c1cb3_idx"
            ),
        ),
    ]
