# Generated by Django 4.2.7 on 2025-12-22 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_auto_20251221_0209"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER update_playlist_time_insert
            AFTER INSERT ON playlist_songs
            BEGIN
                UPDATE playlists SET playlist_updatetime = datetime('now') WHERE playlist_id = NEW.playlist_id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS update_playlist_time_insert;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TRIGGER update_playlist_time_delete
            AFTER DELETE ON playlist_songs
            BEGIN
                UPDATE playlists SET playlist_updatetime = datetime('now') WHERE playlist_id = OLD.playlist_id;
            END;
            """,
            reverse_sql="DROP TRIGGER IF EXISTS update_playlist_time_delete;"
        ),
    ]
