# Generated by Django 4.2.7 on 2025-11-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "user_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="用户ID"
                    ),
                ),
                (
                    "user_name",
                    models.CharField(max_length=64, unique=True, verbose_name="用户名"),
                ),
                (
                    "user_mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "user_avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="avatars/", verbose_name="头像"
                    ),
                ),
                (
                    "user_createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="注册时间"),
                ),
                (
                    "user_type",
                    models.IntegerField(
                        choices=[(0, "普通用户"), (1, "歌手"), (2, "管理员")],
                        default=0,
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否激活"),
                ),
                (
                    "is_staff",
                    models.BooleanField(default=False, verbose_name="是否员工"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(default=False, verbose_name="是否超级管理员"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="最后登录时间"
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="注册时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "用户",
                "verbose_name_plural": "用户",
                "db_table": "users",
            },
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                (
                    "log_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="日志ID"
                    ),
                ),
                (
                    "log_user_name",
                    models.CharField(max_length=64, verbose_name="用户名"),
                ),
                (
                    "log_user_type",
                    models.IntegerField(
                        choices=[(0, "普通用户"), (1, "歌手"), (2, "管理员")],
                        verbose_name="用户类型",
                    ),
                ),
                (
                    "log_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "log_user",
                    models.ForeignKey(
                        db_column="log_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录日志",
                "verbose_name_plural": "登录日志",
                "db_table": "login_logs",
                "ordering": ["-log_time"],
            },
        ),
        migrations.CreateModel(
            name="Follow",
            fields=[
                (
                    "follow_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="关注ID"
                    ),
                ),
                (
                    "follow_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="关注时间"),
                ),
                (
                    "follower",
                    models.ForeignKey(
                        db_column="follower_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="following_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关注者",
                    ),
                ),
                (
                    "following",
                    models.ForeignKey(
                        db_column="followed_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers_set",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被关注者",
                    ),
                ),
            ],
            options={
                "verbose_name": "关注关系",
                "verbose_name_plural": "关注关系",
                "db_table": "follows",
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_name"], name="users_user_na_108efb_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["log_user"], name="login_logs_log_use_fe7922_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginlog",
            index=models.Index(
                fields=["log_time"], name="login_logs_log_tim_aead27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["follower"], name="follows_followe_ca9b09_idx"),
        ),
        migrations.AddIndex(
            model_name="follow",
            index=models.Index(fields=["following"], name="follows_followe_a0ecff_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="follow",
            unique_together={("follower", "following")},
        ),
    ]
