# Generated by Django 5.2.8 on 2025-12-19 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_balance',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='账户余额'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.IntegerField(choices=[(0, '保密'), (1, '男'), (2, '女')], default=0, verbose_name='性别'),
        ),
    ]
