# Generated by Django 4.2.7 on 2025-11-26 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("playlists", "0001_initial"),
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckUserLog",
            fields=[
                (
                    "check_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="审核ID"
                    ),
                ),
                (
                    "check_user_name",
                    models.CharField(max_length=64, verbose_name="用户名"),
                ),
                (
                    "check_user_mobile",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="手机号"
                    ),
                ),
                (
                    "check_user_avatar",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="头像路径"
                    ),
                ),
                ("check_user_type", models.IntegerField(verbose_name="用户类型")),
                (
                    "check_submit_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="审核提交时间"
                    ),
                ),
                (
                    "check_modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="审核修改时间"),
                ),
                (
                    "check_status",
                    models.IntegerField(
                        choices=[(0, "待审核"), (1, "审核通过"), (2, "审核拒绝")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "check_comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "check_admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": 2},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_users",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核管理员",
                    ),
                ),
                (
                    "check_user",
                    models.ForeignKey(
                        db_column="check_user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户审核日志",
                "verbose_name_plural": "用户审核日志",
                "db_table": "check_user_logs",
                "ordering": ["-check_submit_time"],
                "indexes": [
                    models.Index(
                        fields=["check_user"], name="check_user__check_u_ee4ac8_idx"
                    ),
                    models.Index(
                        fields=["check_status"], name="check_user__check_s_71f43a_idx"
                    ),
                    models.Index(
                        fields=["check_submit_time"],
                        name="check_user__check_s_b71954_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckSongLog",
            fields=[
                (
                    "check_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="审核ID"
                    ),
                ),
                (
                    "check_song_name",
                    models.CharField(max_length=128, verbose_name="歌曲名称"),
                ),
                (
                    "check_song_cover",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="歌曲封面路径",
                    ),
                ),
                (
                    "check_song_file",
                    models.CharField(max_length=255, verbose_name="歌曲文件路径"),
                ),
                (
                    "check_song_duration",
                    models.IntegerField(default=0, verbose_name="歌曲时长"),
                ),
                (
                    "check_song_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="歌曲价格",
                    ),
                ),
                (
                    "check_submit_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="审核提交时间"
                    ),
                ),
                (
                    "check_modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="审核修改时间"),
                ),
                (
                    "check_status",
                    models.IntegerField(
                        choices=[(0, "待审核"), (1, "审核通过"), (2, "审核拒绝")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "check_comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "check_admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": 2},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_songs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核管理员",
                    ),
                ),
                (
                    "check_song",
                    models.ForeignKey(
                        db_column="check_song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_logs",
                        to="music.song",
                        verbose_name="歌曲",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌曲审核日志",
                "verbose_name_plural": "歌曲审核日志",
                "db_table": "check_song_logs",
                "ordering": ["-check_submit_time"],
                "indexes": [
                    models.Index(
                        fields=["check_song"], name="check_song__check_s_ee08bc_idx"
                    ),
                    models.Index(
                        fields=["check_status"], name="check_song__check_s_40f22a_idx"
                    ),
                    models.Index(
                        fields=["check_submit_time"],
                        name="check_song__check_s_6987ae_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CheckPlaylistLog",
            fields=[
                (
                    "check_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="审核ID"
                    ),
                ),
                (
                    "check_playlist_name",
                    models.CharField(max_length=128, verbose_name="歌单名称"),
                ),
                (
                    "check_playlist_cover",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="歌单封面路径",
                    ),
                ),
                (
                    "check_playlist_intro",
                    models.TextField(blank=True, null=True, verbose_name="歌单介绍"),
                ),
                (
                    "check_submit_time",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="审核提交时间"
                    ),
                ),
                (
                    "check_modify_time",
                    models.DateTimeField(auto_now=True, verbose_name="审核修改时间"),
                ),
                (
                    "check_status",
                    models.IntegerField(
                        choices=[(0, "待审核"), (1, "审核通过"), (2, "审核拒绝")],
                        default=0,
                        verbose_name="审核状态",
                    ),
                ),
                (
                    "check_comment",
                    models.TextField(blank=True, null=True, verbose_name="审核意见"),
                ),
                (
                    "check_admin",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": 2},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_playlists",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="审核管理员",
                    ),
                ),
                (
                    "check_playlist",
                    models.ForeignKey(
                        db_column="check_playlist_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="check_logs",
                        to="playlists.playlist",
                        verbose_name="歌单",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌单审核日志",
                "verbose_name_plural": "歌单审核日志",
                "db_table": "check_playlist_logs",
                "ordering": ["-check_submit_time"],
                "indexes": [
                    models.Index(
                        fields=["check_playlist"], name="check_playl_check_p_cd1500_idx"
                    ),
                    models.Index(
                        fields=["check_status"], name="check_playl_check_s_fdac66_idx"
                    ),
                    models.Index(
                        fields=["check_submit_time"],
                        name="check_playl_check_s_0c4d03_idx",
                    ),
                ],
            },
        ),
    ]
