# Generated by Django 4.2.7 on 2025-11-26 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "song_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="歌曲ID"
                    ),
                ),
                (
                    "song_name",
                    models.CharField(max_length=128, verbose_name="歌曲名称"),
                ),
                (
                    "song_cover",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="covers/",
                        verbose_name="歌曲封面",
                    ),
                ),
                (
                    "song_file",
                    models.FileField(upload_to="songs/", verbose_name="歌曲文件路径"),
                ),
                (
                    "song_duration",
                    models.IntegerField(default=0, verbose_name="歌曲时长（秒）"),
                ),
                (
                    "song_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        verbose_name="歌曲价格",
                    ),
                ),
                (
                    "song_createtime",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "song_updatetime",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="是否上架"),
                ),
                (
                    "song_singer",
                    models.ForeignKey(
                        limit_choices_to={"user_type": 1},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="歌手",
                    ),
                ),
            ],
            options={
                "verbose_name": "歌曲",
                "verbose_name_plural": "歌曲",
                "db_table": "songs",
                "ordering": ["-song_createtime"],
            },
        ),
        migrations.CreateModel(
            name="BuySong",
            fields=[
                (
                    "buy_song_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="购买记录ID"
                    ),
                ),
                (
                    "buy_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="购买时间"),
                ),
                (
                    "buy_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="购买价格"
                    ),
                ),
                (
                    "song",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bought_by",
                        to="music.song",
                        verbose_name="歌曲",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bought_songs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "购买歌曲",
                "verbose_name_plural": "购买歌曲",
                "db_table": "buy_songs",
            },
        ),
        migrations.CreateModel(
            name="StarSong",
            fields=[
                (
                    "star_song_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="收藏歌曲ID"
                    ),
                ),
                (
                    "star_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="收藏时间"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_by",
                        to="music.song",
                        verbose_name="歌曲",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="starred_songs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "收藏歌曲",
                "verbose_name_plural": "收藏歌曲",
                "db_table": "star_songs",
                "indexes": [
                    models.Index(fields=["user"], name="star_songs_user_id_972c6b_idx"),
                    models.Index(fields=["song"], name="star_songs_song_id_86fe6e_idx"),
                ],
                "unique_together": {("user", "song")},
            },
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["song_name"], name="songs_song_na_2a8800_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["song_singer"], name="songs_song_si_4888f0_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["is_active"], name="songs_is_acti_d12d51_idx"),
        ),
        migrations.AddIndex(
            model_name="buysong",
            index=models.Index(fields=["user"], name="buy_songs_user_id_c3254b_idx"),
        ),
        migrations.AddIndex(
            model_name="buysong",
            index=models.Index(fields=["song"], name="buy_songs_song_id_5b9c49_idx"),
        ),
        migrations.AddIndex(
            model_name="buysong",
            index=models.Index(
                fields=["buy_time"], name="buy_songs_buy_tim_bd4f65_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="buysong",
            unique_together={("user", "song")},
        ),
    ]
