# Generated by Django 4.2.7 on 2025-12-20 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlayHistory",
            fields=[
                (
                    "history_id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="播放记录ID"
                    ),
                ),
                (
                    "play_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="播放时间"),
                ),
                (
                    "play_duration",
                    models.IntegerField(default=0, verbose_name="播放时长(秒)"),
                ),
                (
                    "song",
                    models.ForeignKey(
                        db_column="song_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_history",
                        to="music.song",
                        verbose_name="歌曲",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="play_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "播放记录",
                "verbose_name_plural": "播放记录",
                "db_table": "play_history",
                "ordering": ["-play_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "play_time"],
                        name="play_histor_user_id_1a59df_idx",
                    )
                ],
            },
        ),
    ]
